"""empty message

Revision ID: 12abbd32e0d2
Revises: 3ad09ea0f7dd
Create Date: 2024-03-04 13:18:00.890354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12abbd32e0d2'
down_revision: Union[str, None] = '3ad09ea0f7dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
