"""empty message

Revision ID: 1c0c962bfc90
Revises: 895bada43e99
Create Date: 2024-03-04 12:33:50.622642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c0c962bfc90'
down_revision: Union[str, None] = '895bada43e99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tbl_News', ['id'])
    op.create_unique_constraint(None, 'tbl_NewsSticker', ['news_sticker_association_id'])
    op.create_unique_constraint(None, 'tbl_Note', ['id'])
    op.create_unique_constraint(None, 'tbl_Sticker', ['id'])
    op.create_unique_constraint(None, 'tbl_User', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_User', type_='unique')
    op.drop_constraint(None, 'tbl_Sticker', type_='unique')
    op.drop_constraint(None, 'tbl_Note', type_='unique')
    op.drop_constraint(None, 'tbl_NewsSticker', type_='unique')
    op.drop_constraint(None, 'tbl_News', type_='unique')
    # ### end Alembic commands ###
