"""empty message

Revision ID: 895bada43e99
Revises: 
Create Date: 2024-03-04 12:27:02.940263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '895bada43e99'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_Sticker',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tbl_User',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('login', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('firstname', sa.String(length=64), nullable=False),
    sa.Column('lastname', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('tbl_News',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('userid', sa.BIGINT(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('content', sa.String(length=2048), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userid'], ['tbl_User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('tbl_NewsSticker',
    sa.Column('news_sticker_association_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('news_id', sa.BIGINT(), nullable=True),
    sa.Column('sticker_id', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['tbl_News.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sticker_id'], ['tbl_Sticker.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('news_sticker_association_id'),
    sa.UniqueConstraint('news_sticker_association_id')
    )
    op.create_table('tbl_Note',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('newsid', sa.BIGINT(), nullable=False),
    sa.Column('content', sa.String(length=2048), nullable=True),
    sa.ForeignKeyConstraint(['newsid'], ['tbl_News.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_Note')
    op.drop_table('tbl_NewsSticker')
    op.drop_table('tbl_News')
    op.drop_table('tbl_User')
    op.drop_table('tbl_Sticker')
    # ### end Alembic commands ###
