"""empty message

Revision ID: 0a0d9216ecd9
Revises: fce73a80b50a
Create Date: 2024-03-10 14:45:31.422537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a0d9216ecd9'
down_revision: Union[str, None] = 'fce73a80b50a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('__EFMigrationsHistory')
    op.add_column('tbl_News', sa.Column('userId', sa.BIGINT(), nullable=False))
    op.drop_constraint('tbl_News_userid_fkey', 'tbl_News', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_News', 'tbl_User', ['userId'], ['id'])
    op.drop_column('tbl_News', 'userid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_News', sa.Column('userid', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tbl_News', type_='foreignkey')
    op.create_foreign_key('tbl_News_userid_fkey', 'tbl_News', 'tbl_User', ['userid'], ['id'])
    op.drop_column('tbl_News', 'userId')
    op.create_table('__EFMigrationsHistory',
    sa.Column('MigrationId', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('ProductVersion', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('MigrationId', name='PK___EFMigrationsHistory')
    )
    # ### end Alembic commands ###
