"""empty message

Revision ID: 894a533a2bb7
Revises: 0a0d9216ecd9
Create Date: 2024-03-10 14:47:54.701902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '894a533a2bb7'
down_revision: Union[str, None] = '0a0d9216ecd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_Note', sa.Column('newsId', sa.BIGINT(), nullable=False))
    op.drop_constraint('tbl_Note_newsid_fkey', 'tbl_Note', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_Note', 'tbl_News', ['newsId'], ['id'])
    op.drop_column('tbl_Note', 'newsid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_Note', sa.Column('newsid', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tbl_Note', type_='foreignkey')
    op.create_foreign_key('tbl_Note_newsid_fkey', 'tbl_Note', 'tbl_News', ['newsid'], ['id'])
    op.drop_column('tbl_Note', 'newsId')
    # ### end Alembic commands ###
